name: example
version: 0.0.1


ghc-options: -Wall

executable:
  main: Main.hs
  source-dirs: src

dependencies:
  - base 
  - servant
  - servant-server
  - time
  - text
  - warp
  - wai
  - aeson

